sudo: required
services:
    - docker

before_install:
    - docker build -t mdrozdz17/docker-react -f Dockerfile.dev .

script:
    - docker run mdrozdz17/docker-react npm run test -- -- coverage     